FROM registry.ocp4.example.com:8443/redhattraining/podman-gitea-base:ubi9

ENV GITEA_WORK_DIR=/var/lib/gitea/ \
    GITEA_PORT="3030" \
    HOME="/opt/app-root"

# Configure gitea to run as any user with the root group
# This is necessary when deploying on OpenShift
RUN mkdir -p /var/lib/gitea/{custom,data,log} && \
  mkdir /opt/app-root && \
  chgrp -R 0 /var/lib/gitea/ && \
  chmod -R g=u /var/lib/gitea/ && \
  mkdir /etc/gitea && \
  chgrp -R 0 /etc/gitea && \
  chgrp -R 0 /opt/app-root && \
  chmod -R g=u /etc/gitea && \
  chmod -R g=u /opt/app-root && \
  useradd  \
    --uid 1001 \
    --system \
    --gid 0 \
    --home-dir /opt/app-root \
    --shell /sbin/nologin \
    --comment "Default Application User" \
    default

USER 1001
WORKDIR /opt/app-root
EXPOSE ${GITEA_PORT}

CMD gitea --port ${GITEA_PORT}
